# Generated by Django 2.2.1 on 2019-08-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=200)),
                ('bangla', models.CharField(max_length=200)),
                ('count', models.CharField(max_length=10)),
            ],
        ),
    ]
